:concurrency: 5
:queues:
  - default
  - [mailers, 2]
:scheduler:
  :schedule:
    view_sync_job:
      cron: '0 */12 * * *'  # Chạy mỗi 12 giờ
      class: ViewSyncJob
      queue: default
      description: "Đồng bộ lượt xem từ Redis vào database"
